### PR TITLE
Bump version to 0.9.1

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by samuelcolvin** [comment]
I think I haven't configured autodeploy via ci, so I need to upload to crates manually for now.

**Comment by adriangb** [comment]
Oh sad. Would you mind doing that?

**Comment by samuelcolvin** [comment]
Will do, let's setup. Ci deploy soon.

**Comment by samuelcolvin** [comment]
> Oh sad. Would you mind doing that?

done

> Will do, let's setup. Ci deploy soon.

done #39

**Pull request merged**
