### PR TITLE
Fix overflow issue in `hour` check for timedelta

### PR DESCRIPTION
**Pull request by sydney-runkle**

### CODE REVIEW

**Review by davidhewitt — APPROVED** [review]

**Comment by davidhewitt** [comment]
I think that line got copied from another point in the code, so might be worth having a quick check if other locations are similarly problematic

**Comment by sydney-runkle** [comment]
See https://github.com/pydantic/pydantic-core/actions/runs/9683851266/job/26720269595?pr=1347 for the place where we discovered this error!

**Comment by sydney-runkle** [comment]
Seems like other occurrences are guarded by ascii checks: https://github.com/search?q=repo%3Apydantic%2Fspeedate%20-%20b%270%27&type=code

**Comment by davidhewitt** [comment]
Actually a last minute thought - `wrapping_sub*` may be sufficient here and might be faster because no need to branch. Might be interesting to benchmark 😁

**Comment by davidhewitt** [comment]
(or it could be that the difference comes out as noise)

**Pull request merged**
